name: binder_env
channels:
- defaults
dependencies:
- ipykernel=4.8.2
- pandas=0.22.0
- python=3.6.5
- tensorflow=1.2.1
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-core==4.4.0
  - tensorflow==1.12.0
  - keras==2.2.4
  - astropy==4.0.1
  - numpy==1.16.1
  - scipy==1.2.0
  - scikit-learn==0.20.3
  - scikit-image==0.15.0
  - matplotlib==3.1.0
  - opencv-python  